### ISSUE TITLE
Fix tests (ddimtirov)

### ISSUE THREAD

**Issue by gunnarmorling** [gunnarmorling/1brc#101]
Hey @ddimtirov, since your submission we've added a basic test suite for covering some corner cases (as we discussed already). One of the tests fails for your submission. Could you take a look and fix this so the submission can be re-evaluated? Thx!

```
./test.sh ddimtirov
Validating calculate_average_ddimtirov.sh -- src/test/resources/samples/measurements-1.txt
PT0.029701S

real	0m0.337s
user	0m0.093s
sys	0m0.130s
1c1
< {=0.0/19.8/19.8, Kunming=0.0/19.8/19.8, g=0.0/19.8/19.8, ing=0.0/19.8/19.8, ming=0.0/19.8/19.8, ng=0.0/19.8/19.8, nming=0.0/19.8/19.8}
---
> {Kunming=19.8/19.8/19.8}
```

**Comment by ddimtirov** [comment]
Will do when I get to updating the submission. It will take a few days.

**Comment by ddimtirov** [comment]
Apologies, the commit was done on Windows and the problem is only visible on Linux/Mac.

Addressing in https://github.com/gunnarmorling/1brc/pull/228
