### ISSUE TITLE
Fix tests (kuduwa-keshavram)

### ISSUE THREAD

**Issue by gunnarmorling** [gunnarmorling/1brc#102]
Hey @kuduwa-keshavram, since your submission we've added a basic test suite for covering some corner cases (as we discussed already). One of the tests fails for your submission. Could you take a look and fix this so the submission can be re-evaluated? Thx!

```
./test.sh kuduwa-keshavram
Validating calculate_average_kuduwa-keshavram.sh -- src/test/resources/samples/measurements-1.txt

real	0m0.163s
user	0m0.067s
sys	0m0.037s
Validating calculate_average_kuduwa-keshavram.sh -- src/test/resources/samples/measurements-10.txt

real	0m0.057s
user	0m0.066s
sys	0m0.017s
Validating calculate_average_kuduwa-keshavram.sh -- src/test/resources/samples/measurements-2.txt

real	0m0.054s
user	0m0.060s
sys	0m0.011s
Validating calculate_average_kuduwa-keshavram.sh -- src/test/resources/samples/measurements-20.txt

real	0m0.057s
user	0m0.065s
sys	0m0.015s
Validating calculate_average_kuduwa-keshavram.sh -- src/test/resources/samples/measurements-3.txt

real	0m0.056s
user	0m0.063s
sys	0m0.014s
1c1
< {Bosaso=-15.0/0.0/20.0, Petropavlovsk-Kamchatsky=-9.5/0.0/9.5}
---
> {Bosaso=-15.0/1.3/20.0, Petropavlovsk-Kamchatsky=-9.5/0.0/9.5}
```

**Comment by kuduwa-keshavram** [comment]
> Hey @kuduwa-keshavram, since your submission we've added a basic test suite for covering some corner cases (as we discussed already). One of the tests fails for your submission. Could you take a look and fix this so the submission can be re-evaluated? Thx!
> 
> ```
> ./test.sh kuduwa-keshavram
> Validating calculate_average_kuduwa-keshavram.sh -- src/test/resources/samples/measurements-1.txt
> 
> real	0m0.163s
> user	0m0.067s
> sys	0m0.037s
> Validating calculate_average_kuduwa-keshavram.sh -- src/test/resources/samples/measurements-10.txt
> 
> real	0m0.057s
> user	0m0.066s
> sys	0m0.017s
> Validating calculate_average_kuduwa-keshavram.sh -- src/test/resources/samples/measurements-2.txt
> 
> real	0m0.054s
> user	0m0.060s
> sys	0m0.011s
> Validating calculate_average_kuduwa-keshavram.sh -- src/test/resources/samples/measurements-20.txt
> 
> real	0m0.057s
> user	0m0.065s
> sys	0m0.015s
> Validating calculate_average_kuduwa-keshavram.sh -- src/test/resources/samples/measurements-3.txt
> 
> real	0m0.056s
> user	0m0.063s
> sys	0m0.014s
> 1c1
> < {Bosaso=-15.0/0.0/20.0, Petropavlovsk-Kamchatsky=-9.5/0.0/9.5}
> ---
> > {Bosaso=-15.0/1.3/20.0, Petropavlovsk-Kamchatsky=-9.5/0.0/9.5}
> ```

@gunnarmorling Let me fix it and raise a PR

**Comment by kuduwa-keshavram** [comment]
@gunnarmorling Please Review https://github.com/gunnarmorling/1brc/pull/132

**Comment by gunnarmorling** [comment]
All looking good now, thx!
