### ISSUE TITLE
Measure memory consumption?

### ISSUE THREAD

**Issue by ppuschmann** [gunnarmorling/1brc#120]
Hi,
I like this competition and wonder which effect the different approaches have on the amount of used memory (RAM).

I also triggered by the "always upcoming" benefits of native compilation. 
It would be great to see the differences in the table.

So my question is: Could you memorythe memory consumption of the benchmarks and add it to the table?

**Comment by gunnarmorling** [comment]
It's a nice idea, but I'm deeply under water with this as-is already. I'd prefer to not increase the scope of (my) work for now, but maybe we can do this measurement for all the contenders later on.

**Comment by QBos07** [comment]
Intresting statistics indeed, especially with the noop epsilon GC wich is rather effective in native images. My take had it's peak a ~12 GB but this is heavly implementation dependent. Makes me curios what the speed differnce woud be compared to a normal G1GC?
