### ISSUE TITLE
Smaller file segments is faster

### ISSUE THREAD

**Issue by apete** [gunnarmorling/1brc#121]
At this point it seems difficult to come up with a faster solution (and call it your own), but I believe I can make a contribution.

I took Sam Pullara's solution @spullara and changed one code line from

`int numberOfSegments = Runtime.getRuntime().availableProcessors();`

to

`int numberOfSegments = 20 * Runtime.getRuntime().availableProcessors();`

On my MacBook Air M2 Sam's solution takes about 5.6s. With that one line changed it's about 1s faster. 20 may not be the optimal number on another machine. The key thing is to make the segments smaller, and the number of segments a multiple of the number of cores.

**Comment by gunnarmorling** [comment]
I think that's more a discussion than an issue? Can you close this one and re-open under "Discussions" -> "Ideas"? Thx!

**Comment by apete** [comment]
Yes, you're right
