### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by gunnarmorling** [gunnarmorling/1brc#122]
It should primarly say that one should run (and pass) the test suite and commit any changes from the formatter.

**Comment by gunnarmorling** [comment]
I think we also should add a sentence that one refrain from submitting entries which take longer than 1 min (on whatever machine) to run. It's easy to beat that, while those long runs are killing me.

**Comment by gunnarmorling** [comment]
Also folks should share the time of their implementation vs. the time of the RI on their machine.

**Comment by filiphr** [comment]
I'll see what I can do

**Comment by filiphr** [comment]
I've tried something in #146. Let me know what you think @gunnarmorling. Adding / removing anything is trivial.

**Comment by gunnarmorling** [comment]
Awesome, thx!
