### ISSUE TITLE
Use CSV output format

### ISSUE THREAD

**Issue by AlexanderYastrebov** [gunnarmorling/1brc#14]
Use proper CSV (or semicolon-separated for that matter) output format
```csv
Addis Ababa;33.0;33.0;33.0
Aden;31.1;31.1;31.1,
...
```
instead of weird not-a-json oneliner output.

This would simplify result comparison (diff) between multiple implementations.
This would also enable parsing of results - think of import into database or e.g. database-based implementation.

**Comment by gunnarmorling** [comment]
I agree that this would have been the better way. I'm hesitating though to change the format at this point, to keep different implementations comparable.

**Comment by lluismf** [comment]
The weird not-a-json oneliner is just the map serialized. Writing a CSV output would be extra cost.

**Comment by AlexanderYastrebov** [comment]
@lluismf You are right, serializing result in a portable format is a game-changer and will severely affect processing performance of 10^9 input rows :+1:

**Comment by gunnarmorling** [comment]
Hey, let's keep it friendly :)

I agree that a different output format wouldn't make any difference perf-wise in the grand scheme of things and as said, it would have been the better choice. But I don't think it's that much of an issue to justify changing this while the challenge is running.

So I'd keep this as-is for the time being, and consider it a lesson learned for whenever another challenge of this kind is happening. Thanks all!
