### ISSUE TITLE
Mean or Avg

### ISSUE THREAD

**Issue by ifnesi** [gunnarmorling/1brc#16]
Great project/challenge Gunnar, thank you.
The value to be calculate is the average and not the mean, right?
Based on the baseline (src/main/java/dev/morling/onebrc/CalculateAverage.java) it is average, but just to double-check.

**Comment by padreati** [comment]
How mean and average are different in this case?

**Comment by gunnarmorling** [comment]
Yeah, sorry for being inconsistent with terminology; I should have consistently used "mean" everywhere. But as @padreati is saying, I don't think it makes any actual difference here?

**Comment by ddimtirov** [comment]
Technically, "mean" is one of the possible "average" metrics. Others that come to mind are "median", "mode"
