### ISSUE TITLE
Sort leaderboard by time

### ISSUE THREAD

**Issue by gunnarmorling** [gunnarmorling/1brc#270]
When running _./evaluate2.sh_ for multiple entries, the emitted leaderboard should be ordered by decreasing time.

**Comment by gunnarmorling** [comment]
@hundredwatt, just in case you're up for a follow-up to that eval script change :)

**Comment by gunnarmorling** [comment]
Ah, another question: I reckon we'd need to reset the JDK to the default (`21.0.1-open`) when no prepare script is provided?

**Comment by hundredwatt** [comment]
I can take those 2 items later today

I also want to see if there’s a public GitHub API to get full names from
usernames for the leaderboard

**Comment by gunnarmorling** [comment]
> I can take those 2 items later today

Thank you so much!

> I also want to see if there’s a public GitHub API to get full names from usernames for the leaderboard

Ha, yeah, that might be nice. Not strictly needed though if it turns out too tricky. Showing the handles suffices IMO. What would be nice though is adding that "Notes" column; we could just fake it by saying "GraalVM native binary" when the additional build script is there (as that's its only purpose right now).

**Comment by gunnarmorling** [comment]
Ah, nice! I only hope we don't it GitHub's rate limiter by doing too many calls in a too short period. Don't ask me how I know ;) We'll see.

**Comment by hundredwatt** [comment]
TODOs:

- [ ] Sort leaderboard by time
- [ ] Show name of Github user (maybe with a local cache 😉)
- [ ] we could just fake it by saying "GraalVM native binary" when the additional build script
- [ ]  reset the JDK to the default (21.0.1-open) when no prepare script is provided

**Comment by hundredwatt** [comment]
PR: #274
