### ISSUE TITLE
Seeing others solutions nice but unfair...

### ISSUE THREAD

**Issue by balayanv** [gunnarmorling/1brc#273]
First of all huge respect for pretty insane solutions that people already provided.
But since anyone can take previous solution and do a minor improvement on it, it basically shadows the original contenders work no?

If someone really is tryharding to win this challenge they will wait for last day, take the best solution, add their little improvement on top of it and hope that someone else cant improve it further.

**Comment by balayanv** [comment]
nvm just read the rules lol

**Comment by gunnarmorling** [comment]
Yepp :) "Winning" is just a means to an end. First and foremost, this
challenge is about learning something new, having some fun, and inspiring
others to do the same.

**Comment by balayanv** [comment]
smart move for the company, i would never find your product otherwise...
+ literally everyone who checks this out is either potential customer or hire :D

**Comment by sharpobject** [comment]
> i bet we will get 10-20% best time improvement last day

Well, I had planned on it, but in the last day or so people are getting quite clever.

**Comment by netrunnereve** [comment]
I mean there's nothing forcing you to look at everyone's solutions, unless you want to win I guess? Personally I'm doing this challenge for my own learning and don't plan on looking at the solutions until the contest is over.

**Comment by balayanv** [comment]
to be fair, you can keep improving this, but the code will get so much uglier that its not worth it... i think the way we have it is in the sweet spot... 

but wait for last day... when people start optimising system.out.println

**Comment by gunnarmorling** [comment]
Hehe, we'll see. Some of the folks actually decided not to look at other entries, e.g. @ebarlas. Both is fine really, as, again, the learning experience is what matters the most here. Only thing folks shouldn't do is to re-submit existing entries without any improvements, but it has happened only once so far.

Seems we can close this one?

**Comment by balayanv** [comment]
my bad i thought i closed it

**Comment by balayanv** [comment]
closed
