### ISSUE TITLE
Validate entry names eagerly in evaluate2.sh

### ISSUE THREAD

**Issue by gunnarmorling** [gunnarmorling/1brc#283]
It should be detected at the beginning of the script, whether all passed entry names are valid, i.e. whether a _calculate\_average\_\<entry\>.sh_ exists. And if not, abort the script before running anything.

**Comment by gunnarmorling** [comment]
CC @hundredwatt

**Comment by gunnarmorling** [comment]
To piggyback on this one, the sdk install step should be robust against an empty prepare file. I think right now the grep call fails and aborts the script when it doesn't match anything (can be reproduced by running _evaluate2.sh baseline_.

**Comment by hundredwatt** [comment]
Confirmed, if `prepare_$fork.sh` is present, but has no `sdk use ...`, then `read -r version` fails and exits:

```
+ for fork in '"$@"'
+ '[' -f ./prepare_baseline.sh ']'
+ grep -h '^sdk use' ./prepare_baseline.sh
+ cut '-d ' -f4
+ read -r version
```
