### ISSUE TITLE
Tests fail or don't finish: nstng

### ISSUE THREAD

**Issue by gunnarmorling** [gunnarmorling/1brc#286]
Hey @nstng, could you please run ./test.sh nstng and send a PR to make sure they pass and finish in a short time? We have added some tests to cover some corner cases and this implementation doesn't pass all of them right now. Thanks!

**Comment by nstng** [comment]
Hi, thanks for the heads up. I currently do not have time to work on that - feel free to use https://github.com/gunnarmorling/1brc/pull/295 to revert my submissions if the failing tests are blocking CI. cu :)

**Comment by gunnarmorling** [comment]
Gotcha, removed your entry for the time being. Thanks a lot for participating nevertheless, and of course you're welcome to create a new entry later on if you like.
