### ISSUE TITLE
Proposal: Use Justfile to remove shell scripts

### ISSUE THREAD

**Issue by bxb100** [gunnarmorling/1brc#312]
The repo has now become more popular in Javaer and writes so many calculate* shells, so I'm introducing
[just](https://github.com/casey/just), it is like Makefile, yet, more scriptable

**Comment by AlexanderYastrebov** [comment]
Make is standard, available everywhere a has a huge number of Makefiles and solutions easy to google.

**Comment by gunnarmorling** [comment]
Thx for the proposal, @bxb100. I don't think I'm seeing a huge benefit at this point in time, in particular as we don't really have a situation with several, potentially dependent, tasks. Also I'd like to minimize changes to the toolchain while running this challenge. I am going to close this issue therefore, thx again nevertheless for bringing it up.
