### ISSUE TITLE
Question : does the hardware use hyperthreading?

### ISSUE THREAD

**Issue by balayanv** [gunnarmorling/1brc#369]
if the hyperthreading is enabled its possible that just splitting the total work to N core count will have quite varying actual cpu time, so one worker may finish much sooner and be idle...

Might yield opportunity to improve the best time even further.

**Comment by gunnarmorling** [comment]
No, SMT is disabled. Entries run on eight out of the 32 physical cores of the test machine. I'm planning to do some runs of the Top 5 or so on all cores in a bit.

**Comment by balayanv** [comment]
noted thanks
