### ISSUE TITLE
Under which OS/Distro have the tests being executed? 

### ISSUE THREAD

**Issue by khmarbaise** [gunnarmorling/1brc#42]
Currently the description defines the machine https://github.com/gunnarmorling/1brc?tab=readme-ov-file#evaluating-results but unfortunately not the exact distro which has been used?

**Comment by gunnarmorling** [comment]
Ah yes, good point. I am using Fedora 39. Could you add an entry for that to the FAQ perhaps?

**Comment by gunnarmorling** [comment]
Done.
