### ISSUE TITLE
Clarify rounding semantics

### ISSUE THREAD

**Issue by gunnarmorling** [gunnarmorling/1brc#49]
See https://github.com/gunnarmorling/1brc/pull/5#discussion_r1440578784; CC @AlexanderYastrebov

**Comment by ddimtirov** [comment]
I find that `Math.round((double) x / y) / 10.0` produces the same result as the reference - the important part is to do the division in `double` - addition is guaranteed to be loseless.

Also, I have redone the reference impl as BigDecimal with rounding half-even, and the results don't change (for my file).

[CalculateAverage_BigDecimal.java.txt](https://github.com/gunnarmorling/1brc/files/13828834/CalculateAverage_BigDecimal.java.txt)

**Comment by gunnarmorling** [comment]
Done via #392.

**Comment by AlexanderYastrebov** [comment]
> Done via https://github.com/gunnarmorling/1brc/pull/392.

Unfortunately no, see https://github.com/gunnarmorling/1brc/pull/392/files#r1451734941
