### ISSUE TITLE
Have you deleted the original CalculateAverage.java example?

### ISSUE THREAD

**Issue by Sarkie** [gunnarmorling/1brc#490]
https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage.java

**Comment by tarsa** [comment]
there's https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_baseline.java

**Comment by Sarkie** [comment]
Thanks, the readme needs updating then.

**Comment by gunnarmorling** [comment]
@Sarkie, wanna send a PR for the README? Thx!

**Comment by Sarkie** [comment]
@gunnarmorling 
https://github.com/gunnarmorling/1brc/pull/552
Think this is right

**Comment by gunnarmorling** [comment]
Thx!
