### ISSUE TITLE
Enforce source code formatting

### ISSUE THREAD

**Issue by AlexanderYastrebov** [gunnarmorling/1brc#63]
Fix and enforce (e.g. via PR build check) source code formatting. Currently build produces changes to sources which is annoying when working on own implementation:
```sh
$ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
$ ./mvnw clean verify
...
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   src/main/java/dev/morling/onebrc/CalculateAverage_ebarlas.java
        modified:   src/main/java/dev/morling/onebrc/CalculateAverage_richardstartin.java
        modified:   src/main/java/dev/morling/onebrc/CalculateAverage_seijikun.java
        modified:   src/main/java/dev/morling/onebrc/CalculateAverage_truelive.java
        modified:   src/main/java/dev/morling/onebrc/CreateMeasurements2.java

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by sepe81** [comment]
possible fix: https://github.com/gunnarmorling/1brc/pull/55

**Comment by gunnarmorling** [comment]
Yeah, the formatting already _is_ applied automatically when building with the `qa` profile. Seems just not everyone did that (which is not a surprise, as it's not documented). PR welcome for promoting that plug-in execution from the `qa` profile to the main build section.

**Comment by filiphr** [comment]
The formatting is actually applied by default without any profile. Not sure why people are not committing those changes though

**Comment by gunnarmorling** [comment]
Ah yes, you are right. The `qa` profile is enabled by default. Not sure what else could be done here?

**Comment by AlexanderYastrebov** [comment]
> Not sure what else could be done here?

PR build should fail if formatting was changed during build. I don't know if its possible to do in maven.

**Comment by filiphr** [comment]
I've created PR #99 which would fail the build if formatting is incorrect

**Comment by gunnarmorling** [comment]
Sweet, merged. Thx!
