### ISSUE TITLE
Can we make assumptions about the range of the temperature values?

### ISSUE THREAD

**Issue by chop0** [gunnarmorling/1brc#79]
Since the lowest temperature ever recorded on earth was -89.2 C, and the highest was 56.67 C, can we assume that the temperature will fall in the range [-128, 127]?

**Comment by ddimtirov** [comment]
This would be a reasonable assumption in practice, but not very useful for code, considering that we need one decimal point precision.

**Comment by Hermholtz** [comment]
I would like to know the temperature range, too.

**Comment by gunnarmorling** [comment]
Good question. I've just clarified this in the README:

> Temperature value: non null double between -99.9 (inclusive) and 99.9 (inclusive), always with one fractional digit
