### ISSUE TITLE
Can place names contain semicolons?

### ISSUE THREAD

**Issue by prdoyle** [gunnarmorling/1brc#8]
If they can, [this `split` call](https://github.com/prdoyle/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage.java#L86) is not quite right. If they can't, then [this line from the `README`](https://github.com/gunnarmorling/1brc/blob/566a2ec25a2b415d9c57a976f3a7ac1610d80f5a/README.md?plain=1#L149) is not quite right.

**Comment by gunnarmorling** [comment]
Good call-out, thanks! To keep things simple, names are guaranteed to not contain semicolons. I have updated that FAQ entry accordingly:

> _Q: Can I make assumptions on the names of the weather stations showing up in the data set?_
> A: No, while only a fixed set of station names is used by the data set generator, any solution should work with arbitrary UTF-8 station names (for the sake of simplicity, names are guaranteed to contain no `;` character).

That being said, if one wanted to have semicolons in names, these names would have to be quoted (escaping quotes within names, if needed), as per standard CSV practice.

Gonna close this one as resolved. Please feel free to comment and/or re-open if more clarification is needed. Thanks!
