### ISSUE TITLE
Specify how to set the JDK with SDKman in the launch scripts

### ISSUE THREAD

**Issue by gunnarmorling** [gunnarmorling/1brc#88]
Getting e.g. this one: ./calculate_average_ebarlas.sh: line 18: sdk: command not found

I think it's because `sdk` is a function or something? If anyone has an idea of how to set the SDK reliably in launch scripts, any input would be welcome.

**Comment by AlexanderYastrebov** [comment]
Fixed by #151?

**Comment by gunnarmorling** [comment]
Yepp, that works very reliably now. Closing as resolved. Thx again, @AlexanderYastrebov!
