### ISSUE TITLE
Incorrect leaderboard update

### ISSUE THREAD

**Issue by filiphr** [gunnarmorling/1brc#94]
I think that the leaderboard update with https://github.com/gunnarmorling/1brc/commit/c4d2dc96a8de6b9b27d4dc1a21fe00f236aa2da9 is incorrect. The 2nd entry (mine) has a link to https://github.com/gunnarmorling/1brc/blob/main/src/main/java/dev/morling/onebrc/CalculateAverage_artsiomkorzun.java. 

Checking it a bit better, I see that I was twice in there before. I believe that in the update on https://github.com/gunnarmorling/1brc/commit/37350f1c8edf2d5d4fd55c68c42ad6da42cca886 the entry for @artsiomkorzun uses my name instead of the user whose contribution that is

**Comment by gunnarmorling** [comment]
Good spot, fixed.
